export { default as Charts } from './charts/charts.jsx'
export { default as DashboardHeader } from './dashboard-header/dashboard-header.jsx'
export { default as AddWidget } from './add-widget/add-widget.jsx'
export { default as TopReferals } from './top-referals/top-referals.jsx'
export { default as Stats } from './admission-module-stats/stats.jsx'
export { default as DataWidget } from './data-widget/data-widget.jsx'
export { default as Tasks } from './tasks/tasks.jsx'
export { default as Appointments } from './appointments/appointments.jsx'
export { default as AppointmentsUser } from './appointments/appointments-user.jsx'
export { default as PercentCard } from './dashboard-cards/percent-card.jsx'
export { default as EnqurCard } from './dashboard-cards/enqur-card.jsx'
export { default as DashboardTable } from './dashboard-table/dashboard-table.jsx'
export { default as TotalCards } from './total-cards/total-cards.jsx'

// PLOP IMPORTS
